jobs:
  build:
    docker:
    steps:
      - checkout
      - run:
          command: >
            echo "First Workflow"
  test:
    steps:
      - checkout
      - run:
          command: >
            echo "Second Workflow"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
