jobs:
  build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          command: >
            echo "First Workflow"
  test:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run:
          command: >
            echo "Second Workflow"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
